  sudo: false
  language: python
  python:
    - 3.5
    - 3.6
  matrix:
    include:
      - python: 3.7
        dist: xenial
        sudo: true
  install:
    - pip install poetry
    - poetry install -vvv
  script:
    - poetry run coverage report -m
    - poetry run coverage run --source=lxpy_api -m pytest -v
  after_success:
    - poetry run coveralls